### ISSUE TITLE
Issue with using Faith and Powers' weapon usability

### ISSUE THREAD

**Issue by Velgus** [UnearthedArcana/Will_to_Power#2]
There is a macro not found error trying to install this over Faiths and Powers with its weapon usability component in the latest version of both mods.

I think there is a typo in the fnp_compatibility.tpa file causing it:
```
//check config settings______________________________________________________________
//
 ACTION_IF (FILE_EXISTS_IN_GAME ~d5_fnp_settings.ini~) BEGIN
  INCLUDE ~override/d5_fnp_settings.ini~
    LAM d5_fnp_weapon_usability
 END
```

There doesn't appear to be a macro defined for `d5_fnp_weapon_usability`, and removing that line allows the install to go through successfully. I'm not sure if that line was supposed to be something else though, and removing it may have caused issues.

**Comment by subtledoctor** [comment]
The FnP compatibility has been updated for the newest pre-release versions of FnP. The current version of WtP should work with FnP v0.84, but if you are using the bleeding edge FnP 0.85 builds, then you can grab [this file](https://github.com/subtledoctor/Faiths_and_Powers/blob/master/faiths_and_powers/other_mods/FnP_kit_compatibility/lib/fnp_compatibility.tpa) and drop it into will-to_power/lib/ and then install. 

Once all these pre-release versions become proper releases then everything will be updated in lockstep to work well. But for the moment, it takes a bit more work.

**Comment by Velgus** [comment]
Yeah, I was mixing updated and new versions - when I aligned all to the latest versions, it installed fine.

I came across what seems to be a game-breaking issue in my playthrough, but I'll make a new issue for that.
